name: Build and Upload Artifacts

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.13.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Create artifact directory
        run: mkdir -p artifact

      - name: Copy build artifacts
        run: |
          cp -r .next artifact/
          cp -r public artifact/
          cp package.json artifact/

      - name: Compress artifacts
        run: |
          cd artifact
          tar -czf ../build-artifact.tar.gz .next public package.json
          cd ..

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build-artifact.tar.gz
          retention-days: 30

      - name: Upload to Release (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            .next
            public
            package.json
